# Generated by Django 2.1.4 on 2019-03-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_no', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('professor', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseSpaceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'course_space_time',
            },
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_day', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], default='MON', max_length=3)),
            ],
            options={
                'db_table': 'course_time',
            },
        ),
        migrations.AddField(
            model_name='coursespacetime',
            name='course_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseTime'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_times',
            field=models.ManyToManyField(through='course.CourseSpaceTime', to='course.CourseTime'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'course_no', 'semester', 'university', 'campus')},
        ),
    ]
