# Generated by Django 2.1.4 on 2019-03-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
