# Generated by Django 2.1.4 on 2019-01-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classification', models.CharField(blank=True, max_length=20, null=True)),
                ('course_name', models.CharField(blank=True, max_length=20, null=True)),
                ('professor', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('classroom', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('post_type', models.CharField(blank=True, max_length=10, null=True)),
                ('id_closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_table',
                'managed': False,
            },
        ),
    ]
