# Generated by Django 2.1.4 on 2019-01-24 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('공지사항', '공지사항'), ('스터디/팀플', '스터디/팀플')], default='공지사항', max_length=10)),
                ('is_closed', models.DateTimeField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2019, 1, 24, 17, 29, 44, 653251))),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
