# Generated by Django 2.1.4 on 2019-03-10 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190306_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 22, 36, 19, 311127)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 22, 36, 19, 310128)),
        ),
    ]
