# Generated by Django 2.1.4 on 2019-01-31 20:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 20, 8, 14, 650611))),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.Post')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
