# Generated by Django 2.1.4 on 2019-01-31 13:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 13, 58, 53, 430622))),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.DO_NOTHING, to='board.Post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
