# Generated by Django 2.1.4 on 2019-01-31 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 15, 12, 28, 181532)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
